version: '3'

services:
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
    user: 0:0
    volumes:
      - ./:/var/lib/grafana
    environment:
      - GF_LOG_MODE=console
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=DEV
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=https
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.rule=Host(`grafana.dev.run`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - traefik

networks:
  traefik:
    external: true