version: '3.8'

services:
  uptime_kuma:
    container_name: uptime
    image: louislam/uptime-kuma
    restart: always
    volumes:
      - ./:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime.entrypoints=https
      - traefik.http.routers.uptime.tls=true
      - traefik.http.routers.uptime.rule=Host(`uptime.dev.run`)
      - traefik.http.services.uptime.loadbalancer.server.port=3001
    networks:
      - traefik

networks:
  traefik:
    external: true
