version: '3'

services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.rule=Host(`docker.dev.run`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - traefik

networks:
  traefik:
    external: true
