version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 1000:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxxxxxxxxxx
    command:
      # - --require_secure_transport=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - traefik

networks:
  traefik:
    external: true
